(define-actor sem ((h nil)) 
  (guard (list :get target) (null h)) (progn (send target t) 
					     (setf h target))
  (guard (list :get target)) (send target nil)
  (list :release) (setf h nil))

(define-actor customer (semaphore) 
  (list t) (progn (format t "Critical code")
		  (send semaphore :release))
  (list nil) (send semaphore (list :get self)))